version: "3.9"

services:
  #MySql Database
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - ./mysql_db.env
    volumes:
      - ./mysql_db:/var/lib/
      - ./docker/mssql/PE7045_Oct21_cinema.sql:/docker-entrypoint-initdb.d/create_db.sql
    command: --default-authentication-plugin=mysql_native_password


  app:
    image: php
    build: ./cinema_app
    container_name: php_app
    restart: unless-stopped
    working_dir: /var/www/cinema_app
    volumes:
      - ./cinema_app:/var/www/cinema_app
    depends_on:
      - mysql_db


  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    tty: true
    volumes:
      - ./cinema_app:/var/www/cinema_app
      - ./docker/nginx/local_http_app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    depends_on:
      - app
